//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFALogisticasInversas.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3F19C_OpenGateEntities : DbContext
    {
        public DB_A3F19C_OpenGateEntities()
            : base("name=DB_A3F19C_OpenGateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dettarimasskus> dettarimasskus { get; set; }
        public virtual DbSet<logisticainversa> logisticainversa { get; set; }
        public virtual DbSet<origenlogistica> origenlogistica { get; set; }
        public virtual DbSet<skus> skus { get; set; }
        public virtual DbSet<skusbenavides> skusbenavides { get; set; }
        public virtual DbSet<skusinventarios> skusinventarios { get; set; }
        public virtual DbSet<statuslogisticasinversas> statuslogisticasinversas { get; set; }
        public virtual DbSet<statustarimas> statustarimas { get; set; }
        public virtual DbSet<tarimas> tarimas { get; set; }
        public virtual DbSet<uom> uom { get; set; }
    }
}
